development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  channel_prefix: meme_production
  url: "<%= ENV['REDIS_URL'] %>"
  ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE }
