development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  channel_prefix: meme_staging
  url: "rediss://default:AVNS_tjkgiVs0ubFNLpb8iKg@memee-redis-sfo3-57242-do-user-14425281-0.b.db.ondigitalocean.com:25061"
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>
