amazon:
  service: S3
  access_key_id: <%= ENV["BUCKETEER_AWS_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV['BUCKETEER_AWS_SECRET_ACCESS_KEY'] %>
  bucket: <%= ENV['BUCKETEER_BUCKET_NAME'] %>
  endpoint: https://sfo3.digitaloceanspaces.com
  region: unused